package com.seeker.share.security;

public enum PermissionCode {
	SHARE_READ,
	SHARE_CREATE,
	SHARE_DOWNLOAD,
	SHARE_DELETE,
	SHARE_CLEAR,
	DEVICE_READ,
	DOCUMENT_READ,
	DOCUMENT_WRITE,
	DOCUMENT_MANAGE,
	USER_MANAGE,
	ROLE_MANAGE
}
